package:
    name: freesasa
    version: 2.0.2

source:
  fn: freesasa-2.0.2.tar.gz
  url: https://github.com/mittinatten/freesasa/releases/download/2.0.2/freesasa-2.0.2.tar.gz
  md5: 917d4ddf4f1975ac69c8977479430db3
#  patches:
#    - update_msvc_sln.patch           [win]
#    - subpixel.patch

build:
  number: 0

requirements:
    build:
        - python
        - setuptools
        - cython
        - mingw [win]
    run:
        - python

about:
  home: https://github.com/mittinatten/freesasa
  license: MIT
