package:
    name: freesasa
    version: 2.0.1

source:
  fn: freesasa-2.0.1.tar.gz
  url: https://github.com/mittinatten/freesasa/releases/download/2.0.1/freesasa-2.0.1.tar.gz
  md5: 3e705837a33ec891868b2512d9e26be2
#  patches:
#    - update_msvc_sln.patch           [win]
#    - subpixel.patch

build:
  number: 1

requirements:
    build:
        - python
        - setuptools
        - Cython
    run:
        - python

about:
  home: https://github.com/mittinatten/freesasa
  license: MIT
